name: Build and Publish Artifacts

on:
  push:
    branches:
      - main # Adjust this to match your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # You can adjust the Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Build Vue.js app
      run: npm run build

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: vuejs-build
        path: dist # Adjust this to match your build output directory
