name: Build and Package Vue.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Vue.js project
        run: npm run build

      - name: Package artifacts
        run: |
          mkdir -p artifacts
          cp -r dist artifacts/
          zip -r artifacts.zip artifacts/
        if: success()

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: artifacts.zip
